name: Generate Mocks
on:
  workflow_dispatch:
    inputs:
      username:
        description: "username"
        type: string
        required: true
      password:
        description: "password"
        type: secret
        required: true
      impersonate:
        description: "Impersonate user"
        type: string
        required: false
      branch:
        description: "Branch to commit changes to"
        type: string
        default: "main"
        required: false
jobs:
  generate-mocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - name: Set remote to SSH
        run: |
          git remote set-url origin ${{ secrets.ssh }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install --dev
      - name: Generate mocks
        run: |
          pipenv run python make_mocks.py -u "${{ inputs.username }}" -p "${{ inputs.password }}" -i "${{ inputs.impersonate }}"
      - name: Check for changes
        run: |
          if git status --porcelain; then
            echo "Changes detected"
          else
            echo "No changes detected"
            exit 0
          fi
      - name: Add changes
        run: |
          git add .
      - name: Commit changes
        run: |
          git commit -m "Update mocks"
      - name: Push changes
        run: |
          git push origin ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up
        run: |
          pipenv --rm || true
          rm -rf .venv || true
          git reset --hard HEAD
          git clean -fdx
        continue-on-error: true
      - name: Notify completion
        run: |
          echo "Mock generation and commit process completed successfully."
      - name: Notify failure
        if: failure()
        run: |
          echo "Mock generation or commit process failed."
          exit 1
        continue-on-error: true
